services:
  - type: web
    name: perplexity-chatbot-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PERPLEXITY_API_KEY
        sync: false  # This will be set manually in Render dashboard
      - key: FRONTEND_URL
        sync: false  # This will be set manually in Render dashboard